const CLASS ={
	NPC:{
		NAME:"Nonheroic",
		REFRENCE:"NPC",
		ref:0,
		fort:0,
		will:0,
		BAB: .75,
		LEVEL:0,
		HITDICE:4,
		STARTINGHP:4
	},
	JEDI:{
		NAME:"Jedi",
		REFRENCE:"JEDI",
		ref:1,
		fort:1,
		will:1,
		BAB: 1,
		CLASS_SKILLS:[SKILL.ACROBATICS,SKILL.ENDURANCE,SKILL.INITIATIVE,SKILL.KNOWLEDGE_BUREAUCRACY,SKILL.KNOWLEDGE_GALACTIC_LORE,SKILL.KNOWLEDGE_LIFE_SCIENCES,SKILL.KNOLEDGE_PHYSICAL_SCIENCES,SKILL.KNOLEDGE_SOCIAL_SCIENCES,SKILL.KNOWLEDGE_TACTICS,SKILL.KNOWLEDGE_TECHNOLOGY,SKILL.PERCEPTION,SKILL.PILOT,SKILL.USE_THE_FORCE],
		NUMBER_OF_TRAINED_SKILLS: 2,
		LEVEL:0,
		HITDICE:10,
		STARTINGHP:30
	},
	NOBLE:{
		NAME:"Noble",
		REFRENCE:"NOBLE",
		ref: 1,
		fort: 0,
		will: 2,
		BAB: .75,
		LEVEL:0,
		HITDICE:6,
		STARTINGHP:18
	},
	SCOUT:{
		NAME:"Scout",
		REFRENCE:"SCOUT",
		ref:2,
		fort:1,
		will:0,
		BAB: .75,
		LEVEL:0,
		HITDICE:8,
		STARTINGHP:24
	},
	SCOUNDREL:{
		NAME:"Scoundrel",
		REFRENCE:"SCOUNDREL",
		ref:2,
		fort:0,
		will:1,
		BAB: .75,
		LEVEL:0,
		HITDICE:6,
		STARTINGHP:18
	},
	SOLDIER:{
		NAME:"Soldier",
		REFRENCE:"SOLDIER",
		ref:1,
		fort:2,
		will:0,
		BAB:1,
		LEVEL:0,
		HITDICE:10,
		STARTINGHP:30
	},
	BEAST:{
		NAME:"Beast",
		REFRENCE:"BEAST",
		ref:0,
		fort:2,
		will:0,
		BAB:.75,
		LEVEL:0,
		HITDICE:8,
		STARTINGHP:8
	}
}

